[package]
name = "analyze_rhythm_eval"
version = "0.1.0"
description = "Evaluation framework for AudioAnalyzeRhythmDetector"
edition = "2021"

[[bin]]
name = "evaluate"
path = "src/evaluate.rs"

[dependencies]
hound = "3.4"

[build-dependencies]
cmake = "0.1.31"